# Generated by Django 5.1 on 2024-08-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, verbose_name='Device Name')),
                ('average_before_normalization', models.FloatField(verbose_name='Average Before Normalization')),
                ('average_after_normalization', models.FloatField(verbose_name='Average After Normalization')),
                ('data_size', models.IntegerField(verbose_name='Data Size')),
                ('raw_data', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Elements',
            },
        ),
    ]
